# Generated by Django 4.2.2 on 2023-07-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianpemasok',
            name='harga_pengiriman',
        ),
        migrations.RemoveField(
            model_name='penilaianpemasok',
            name='kualitas_harga',
        ),
        migrations.RemoveField(
            model_name='penilaianpemasok',
            name='kualitas_pengiriman',
        ),
        migrations.CreateModel(
            name='PrioritasPemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kualitas_harga', models.IntegerField(null=True)),
                ('kualitas_pengiriman', models.IntegerField(null=True)),
                ('harga_pengiriman', models.IntegerField(null=True)),
                ('umkm', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioritas_pemasok_umkm', to='base.umkm')),
            ],
        ),
    ]
