# Generated by Django 4.2.2 on 2023-07-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_penilaianpemasok_harga_pengiriman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penilaianpemasok',
            old_name='harga',
            new_name='biaya',
        ),
        migrations.RenameField(
            model_name='penilaianpemasok',
            old_name='nama_pemasok',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='prioritaspemasok',
            old_name='harga_pengiriman',
            new_name='biaya_pengiriman',
        ),
        migrations.RenameField(
            model_name='prioritaspemasok',
            old_name='kualitas_harga',
            new_name='kualitas_biaya',
        ),
    ]
