# Generated by Django 4.2.2 on 2023-07-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_harga_penilaianpemasok_biaya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakta',
            name='owner',
        ),
    ]
