# Generated by Django 4.2.2 on 2023-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_fakta_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koperasi',
            name='tgl_penginputan',
        ),
        migrations.AlterField(
            model_name='perijinan',
            name='nomor',
            field=models.IntegerField(),
        ),
    ]
