# Generated by Django 4.2.2 on 2023-07-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_koperasi_tgl_penginputan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KontakPelayanan',
            new_name='KontakLayanan',
        ),
    ]
