# Generated by Django 4.2.2 on 2023-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pengaduan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='biaya_pengiriman',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='kualitas_biaya',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='kualitas_pengiriman',
            field=models.CharField(max_length=1),
        ),
    ]
