# Generated by Django 4.2.2 on 2023-07-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_prioritaspemasok_biaya_pengiriman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='biaya_pengiriman',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='kualitas_biaya',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prioritaspemasok',
            name='kualitas_pengiriman',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
