# Generated by Django 4.2.2 on 2023-07-19 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_prioritaspemasok_biaya_pengiriman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisprodukumkm',
            name='komoditi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
