# Generated by Django 4.2.2 on 2023-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_jenisprodukumkm_komoditi_alter_umkm_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisprodukkoperasi',
            name='nama_produk',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jenisprodukumkm',
            name='nama_produk',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='perijinan',
            name='nomor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
