# Generated by Django 4.2.2 on 2023-07-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_jenisprodukkoperasi_nama_produk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umkm',
            old_name='nama_usaha',
            new_name='nama',
        ),
    ]
